version: 2

sources:
  - name: raw
    database: AIRBNB
    tables:

      - name: raw_listings
      
      - name: raw_reviews
        loaded_at_field: date
        freshness: 
          warn_after:
            count: 1
            period: hour
          error_after:
            count: 24
            period: hour
        

      - name: raw_hosts